{
 "title": "JWT Pizza Service",
 "time": { "from": "2026-03-19T22:15:20.020Z", "to": "2026-03-19T23:35:41.666Z" },
 "panels": [
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizzaRevenue_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza creation latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(pizzaCreationLatency_milliseconds_total{source=\"jwt-pizza-service\"}[1m]))\n/\nsum(rate(pizzaCreationRequests_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "milliseconds"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(serviceLatency_milliseconds_total{source=\"jwt-pizza-service\"}[1m]))\n/\nsum(rate(serviceRequests_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "milliseconds"
    }
   ]
  },
  {
   "title": "Pizza purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(pizzasSold_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Sold"
    },
    {
     "expr": "pizzaCreationFailures_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(authAttempts_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "activeUsers_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "Active users"
    }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum(rate(requests_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (method) (rate(requests_total{source=\"jwt-pizza-service\", method!=\"\"}[1m]))",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}